
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

spring.mail.host=${DB_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Show the SQL queries in the console log
spring.jpa.show-sql=true
# Pretty-print the SQL statements so they are easy to read
spring.jpa.properties.hibernate.format_sql=true
# Log the actual parameter values (like the UUID, retry count, status) replacing the '?' placeholders
logging.level.org.hibernate.orm.jdbc.bind=trace