CREATE TABLE IF NOT EXIST sheduler_users(
    id BIGINT AUTO_INCREMENT  PRIMARY KEY,
    api_name VARCHAR(255) NOT NULL,
    retry_count INT DEFAULT 0,
    error_message TEXT,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTSMP ON UPDATE CURRENT_TIMESTAMP
);